### ISSUE TITLE
No luck in running demo 2.x

### ISSUE THREAD

**Issue by outluch** [websanova/vue-auth#207]
I did git clone this repo.
cd demos/2.x
npm install
npm run demo

got 5 errors from webpack:
```
ERROR in /Users/outluch/code/_upwork/coins/_res/vue-auth/drivers/auth/bearer.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/outluch/code/_upwork/coins/_res/vue-auth/drivers/auth"
```

```
node -v
v8.2.1
```

**Comment by websanova** [comment]
Bit strange, try to remove node modules folder and try again maybe...or
maybe you have some package installed globally?

**Comment by don41382** [comment]
Same problem/error over here.

```
ERROR in /private/tmp/vue-auth/drivers/router/vue-router.2.x.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/private/tmp/vue-auth/drivers/router"
    at /private/tmp/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/private/tmp/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/private/tmp/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/private/tmp/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:359:12)
    at File.initOptions (/private/tmp/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/private/tmp/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/private/tmp/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/private/tmp/vue-auth/demos/2.x/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/private/tmp/vue-auth/demos/2.x/node_modules/babel-loader/index.js:131:12)
 @ ./src/app.js 110:12-64
```

```
nove -v
v8.1.2
```

**Comment by websanova** [comment]
Yes, will take a look this weekend

**Comment by websanova** [comment]
Btw do you have any packages installed globally? Like weback or Babel?

**Comment by websanova** [comment]
Bit strange, you did an `npm install` right in the 2.x folder right?

https://github.com/websanova/vue-auth/blob/master/docs/Demos.md#demos

Also I've update some of the modules to the latest so maybe that helps if you grab the latest.

Also can you check if your demos/2.x/node_modules folder contains "transform-runtime" folder ?

**Comment by don41382** [comment]
@websanova Sorry for the delay, here are my global packages:

```

**Comment by don41382** [comment]
here my steps:

```
git clone https://github.com/websanova/vue-auth
Cloning into 'vue-auth'...
[...]

# cd vue-auth/demos/2.x/
# npm install
npm install

> fsevents@1.1.2 install /private/tmp/vue-auth/demos/2.x/node_modules/fsevents
> node install

Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN 2.x No description
npm WARN 2.x No repository field.
npm WARN 2.x No license field.

added 656 packages in 16.352s
```

```
npm run demo

> @ demo /private/tmp/vue-auth/demos/2.x
> webpack-dev-server --https --host=0.0.0.0 --port=8002

 https://0.0.0.0:8002/webpack-dev-server/
webpack result is served from /
content is served from /private/tmp/vue-auth/demos/2.x/public
404s will fallback to /index.html
Hash: e74e5abad4a0625ac8c4
Version: webpack 1.13.1
Time: 922ms
[..]
ERROR in /private/tmp/vue-auth/drivers/auth/bearer.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/private/tmp/vue-auth/drivers/auth"
[...]
```

looking for all modules with t
```
# ls node_modules/t*
tapable/            through/            through2/           time-stamp/         timers-browserify/  to-fast-properties/ trim-right/         tty-browserify/     type-is/
```

**Comment by websanova** [comment]
Ok, I've update this issue, you will need the latest `v2.16.3-beta` and follow the new demo instructions.
