### ISSUE TITLE
Error when trying to run 2.x demo

### ISSUE THREAD

**Issue by ssuess** [websanova/vue-auth#212]
When I go into the 2.x folder and type `npm install`, I get these warnings
```
npm WARN vue-axios@2.0.2 requires a peer of vue@>= 1.0.0 but none was installed.
npm WARN 2.x No description
npm WARN 2.x No repository field.
npm WARN 2.x No license field.
```
And then when I use `npm run demo` I get a long string of errors and a "webpack: Failed to compile." warning and a failure to launch the demo.

is there something else required to be installed for the demo?

**Comment by guilhermewaess** [comment]
FYI
Somebody already opened a issue #207  for this error :)

**Comment by websanova** [comment]
I just did a full reinstall of the packages, do you have anything installed globally like webpack?

**Comment by ssuess** [comment]
here are my global installs:

/usr/local/lib
├── grunt-cli@1.2.0
├── npm@4.2.0
└── vue-cli@2.8.2

**Comment by ssuess** [comment]
I just did a full reinstall as well, and here are all the errors I get when trying to run the demo (2.x):

```
ERROR in /Users/stephen/vue-auth-master/src/index.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/stephen/vue-auth-master/src"
    at /Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:359:12)
    at File.initOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:131:12)
 @ ./src/app.js 106:8-40

ERROR in /Users/stephen/vue-auth-master/drivers/auth/bearer.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/stephen/vue-auth-master/drivers/auth"
    at /Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:359:12)
    at File.initOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:131:12)
 @ ./src/app.js 107:10-52

ERROR in /Users/stephen/vue-auth-master/drivers/router/vue-router.2.x.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/stephen/vue-auth-master/drivers/router"
    at /Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:359:12)
    at File.initOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:131:12)
 @ ./src/app.js 110:12-64

ERROR in /Users/stephen/vue-auth-master/drivers/http/vue-resource.1.x.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/stephen/vue-auth-master/drivers/http"
    at /Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:359:12)
    at File.initOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:131:12)
 @ ./src/app.js 108:10-62

ERROR in /Users/stephen/vue-auth-master/src/lib/cookie.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/Users/stephen/vue-auth-master/src/lib"
    at /Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:172:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:150:20)
    at OptionManager.mergeOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:224:36)
    at OptionManager.init (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:359:12)
    at File.initOptions (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:221:65)
    at new File (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:141:24)
    at Pipeline.transform (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/stephen/vue-auth-master/demos/2.x/node_modules/babel-loader/index.js:131:12)
 @ ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/Home.vue 7:14-57
webpack: Failed to compile.
```

**Comment by ssuess** [comment]
not sure if it matters, but when I run `npm install @websanova/vue-auth` it tells me it installs `@websanova/vue-auth@2.15.1-beta`

**Comment by ssuess** [comment]
Ok, I think I see the problem now, at least in my case. I was downloading the repo and then running the install and demo (inside the demo folder), and getting the errors above. When I install the component inside a project (or outside, where it just creates a node_modules folder), it works. Hope this helps someone else who was having the same problems.

**Comment by websanova** [comment]
Well, you have to npm install each individual demo...

**Comment by ssuess** [comment]
I was doing that, that wasn't the problem in this case.

**Comment by websanova** [comment]
https://github.com/websanova/vue-auth/blob/master/docs/Demos.md#demos

**Comment by ssuess** [comment]
To clarify, here is exactly what I did originally (that failed):
1. Downloaded the repo
2. cd into demo 2.x folder
3. run npm install
4. run npm run demo

And what I did that worked:
1. run npm install @websanova/vue-auth
2. cd into node_modules/@websanova/vue-auth/demos/2.x/
3. run npm install
4. run npm run demo

**Comment by websanova** [comment]
Right, well the demos are standalone....

**Comment by jericopulvera** [comment]
followed the steps and did npm run demo.
I go to the url and paste the https://192.168.10.10:8001

I get took to long to load the page error.

**Comment by websanova** [comment]
Which demo did you run?

On Aug 8, 2017 23:43, "Jerico Pulvera" <notifications@github.com> wrote:

followed the steps and did npm run demo.
I go to the url and paste the https://192.168.10.10:8001

I get took to long to load the page error.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/websanova/vue-auth/issues/212#issuecomment-320996403>,
or mute the thread

**Comment by DanielMuller** [comment]
Seems that this is due to webpack resolving modules relative to the file path. Files outside the demo path, like `../../../src/index.js`, aren't able to load modules in demo. Like here: https://github.com/websanova/vue-auth/blob/772eeda22f0676aa37051077a551edf2dab4b25b/demos/2.x/src/app.js#L98-L102
I tried several variations of `resolve` in webpack.config.js without success.
I finally was able to get the 2.x demo working by copying `node_modules` in the demo to the project root.

**Environment:**
```
  >$ node -v
  v8.4.0
  >$ npm -v
  5.3.0
  >$ npm -g ls --depth 0
  └── npm@5.3.0
```
**Working demo:**
```bash
  git clone git@github.com:websanova/vue-auth.git
  cd vue-auth/demos/2.x
  npm i
  cp -a node_modules ../../
  npm run demo
```
