### ISSUE TITLE
Demo failed to compile

### ISSUE THREAD

**Issue by tburschka** [websanova/vue-auth#368]
I tried the demo for the 2.x but it failed to compile
```
ERROR in /home/some/dir/vue-auth/drivers/auth/bearer.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/home/some/dir/vue-auth/drivers/auth"
    at /home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:163:20)
 @ ./src/app.js 107:10-52

ERROR in /home/some/dir/vue-auth/drivers/http/vue-resource.1.x.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/home/some/dir/vue-auth/drivers/http"
    at /home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:163:20)
 @ ./src/app.js 108:10-62

ERROR in /home/some/dir/vue-auth/src/index.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/home/some/dir/vue-auth/src"
    at /home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:163:20)
 @ ./src/app.js 106:8-40

ERROR in /home/some/dir/vue-auth/drivers/router/vue-router.2.x.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/home/some/dir/vue-auth/drivers/router"
    at /home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:163:20)
 @ ./src/app.js 110:12-64

ERROR in /home/some/dir/vue-auth/src/lib/cookie.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/home/some/dir/vue-auth/src/lib"
    at /home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/home/some/dir/vue-auth/demos/2.x/node_modules/babel-loader/lib/index.js:163:20)
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/pages/Home.vue 7:14-57
webpack: Failed to compile.

```

**Comment by Anupam-** [comment]
same issue here

**Comment by websanova** [comment]
Did you run npm install in the root and in the demo package?
