### ISSUE TITLE
error at build because vue-auth not compiled to es5 (in SSR mode with nuxt)

### ISSUE THREAD

**Issue by darkylmnx** [websanova/vue-auth#560]
just built a nuxt project with vue-auth added, since, the build fails.

```bash
6:59:45 AM: ℹ Generating pages
6:59:45 AM:  ERROR   /connexion
6:59:45 AM: /opt/build/repo/node_modules/@websanova/vue-auth/src/index.js:1
6:59:45 AM: (function (exports, require, module, __filename, __dirname) { import Auth from './auth.js';
6:59:45 AM:                                                                      ^^^^
6:59:45 AM: SyntaxError: Unexpected identifier
6:59:45 AM:     at new Script (vm.js:83:7)
```

It seems vue-auth is not compiled to es5 even when babel is in the project, this seems to break generation with nuxt and doesn't work in SSR mode either.

When I activate vue-auth in client-mode only it works on client but still breaks in SSR more.

```bash
i Generating pages                                                                            15:29:23
error Cannot read property 'ready' of undefined                                               15:29:24

  at server.js:1:431802
  at m.render (server.js:1:2084)
  at createFunctionalComponent (node_modules\vue\dist\vue.runtime.common.dev.js:3052:30)
  at createComponent (node_modules\vue\dist\vue.runtime.common.dev.js:3225:12)
  at _createElement (node_modules\vue\dist\vue.runtime.common.dev.js:3427:13)
  at createElement (node_modules\vue\dist\vue.runtime.common.dev.js:3347:10)
  at vm.$createElement (node_modules\vue\dist\vue.runtime.common.dev.js:3487:54)
  at Proxy.render (server.js:1:432195)
  at Vue._render (node_modules\vue\dist\vue.runtime.common.dev.js:3538:22)
  at resolve (node_modules\vue-server-renderer\build.dev.js:8656:28)
  at waitForServerPrefetch (node_modules\vue-server-renderer\build.dev.js:8287:3)
  at render (node_modules\vue-server-renderer\build.dev.js:8658:5)
  at Object.renderToString (node_modules\vue-server-renderer\build.dev.js:9183:9)
  at node_modules\vue-server-renderer\build.dev.js:9549:22
error Cannot read property 'ready' of undefined                                               15:29:24

  at server.js:1:431802
  at m.render (server.js:1:2084)
  at createFunctionalComponent (node_modules\vue\dist\vue.runtime.common.dev.js:3052:30)
  at createComponent (node_modules\vue\dist\vue.runtime.common.dev.js:3225:12)
```

**Comment by websanova** [comment]
yea, I haven't had time to setup a build script for it yet. So it's just as is with the es6 syntax which I guess is incompatible with nuxt. Bit strange, would think nuxt is a bit more up to date.

Anyway, will try to get to that in the next week or two, or you can submit a pull request as well if you have time.

**Comment by darkylmnx** [comment]
Well it seems to be incompatible during SSR because native SSR doesn't understand "import" keyword. I got it to work by forcing transpilation as described here https://fr.nuxtjs.org/guide/plugins/#es6-plugins.

The other issue I had with nuxt (but it would be the same with any SSR env) is that vue-auth isn't SSR ready, as you use localStore and cookie which are on the window and document objects that do no exist during ssr. That breaks the router and functions in templates like `$auth.check()` etc.

I had to shim it by doing something like:
```javascript
// in nuxt.config.js
export default {
  plugins: [
    './plugins/auth.client.js', // loads only on client
    './plugins/auth.server.js', // loads only during ssr/server
  ],
}
```
```javascript
// in auth.server.js
// always return ready, no user logged in, resolve load directly,
import Vue from 'vue';

Vue.prototype.$auth = {
  ready() {
    return true;
  },
  check() {
    return false;
  },
  load() {
    return Promise.resolve();
  },
  user() {
    return null;
  },
};
```

```javascript
// in auth.client.js
import Vue from 'vue';
import VueAuth from '@websanova/vue-auth';
import auth from '@websanova/vue-auth/drivers/auth/bearer.js';
import http from '@websanova/vue-auth/drivers/http/axios.1.x.js';
import router from '@websanova/vue-auth/drivers/router/vue-router.2.x.js';
import { api } from '@/plugins/axios';

export default ({ app }, inject) => {
  Vue.axios = api; // my own api instance
  Vue.router = app.router;
  Vue.use(VueAuth, {
    auth,
    http,
    router,
  });
};
```

Feel free to add this to the cookbook if you find it interesting.
In the new docs, you didn't precise that the router instance and axios needed to be present on the Vue class, or at least I didn't see it. I remembered from that from the old docs and through some errors.

**Comment by websanova** [comment]
Ok, will look into that.

For now I've added a built so there are proper es6 and es5 version of each file.

Haven't tested es5, but "should" work.

https://websanova.com/docs/vue-auth/guides/startup#setup
