### ISSUE TITLE
npm/yarn install returns 404

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [websanova/vue-auth#584]
Hi,

when trying to install the package CLI returns a 404 error on all versions:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@websanova/vue-auth' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose npm-session d158d53426e26199
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/@websanova%2fvue-auth 206ms
8 silly fetchPackageMetaData error for @websanova/vue-auth@latest 404 Not Found: @websanova/vue-auth@latest
9 timing stage:rollbackFailedOptional Completed in 3ms
10 timing stage:runTopLevelLifecycles Completed in 3382ms
11 verbose stack Error: 404 Not Found: @websanova/vue-auth@latest
11 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:705:18)
11 verbose stack     at tryOnImmediate (timers.js:676:5)
11 verbose stack     at processImmediate (timers.js:658:5)
12 verbose cwd /Volumes/Workspace/marketplace
13 verbose Darwin 18.2.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@websanova/vue-auth"
15 verbose node v10.13.0
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: @websanova/vue-auth@latest
19 verbose exit [ 1, true ]
```

I tried it with `latest`, `3.2.2-beta`and `2.2.1-beta`.
Any idea why this happens?

Thx in advance

**Comment by straurob** [comment]
Could you post the command you executed to install the package?

As far as I can see from the logs, the URL itself is correct and returns result:  
`https://registry.npmjs.org/@websanova%2fvue-auth`

Do you have trouble with other packages as well? Maybe it's some kind of internal network issue?

**Comment by hurradieweltgehtunter** [comment]
I used `npm install @websanova/vue-auth` as stated here: https://websanova.com/docs/vue-auth/guides/startup
We tried on 3 different locations (2 local computers, 1 CI system) and everywhere the same result.

**Comment by hurradieweltgehtunter** [comment]
After multiple tests yesterday I tried it today and it works again.
